'use strict';
/* cloud-init user-data for freshly provisioned Ubuntu/Debian VMs. Creates a
   `deploy` user with the given public key and passwordless sudo limited to
   service reloads, installs the stack the recipe names, opens 22/80/443 and
   prepares /var/www/<app> owned by deploy. Kept deliberately small and
   readable: it is shown to the user before provisioning. */

const RECIPES = {
  base: { label: 'Base (nginx only)', packages: ['nginx', 'git', 'curl', 'unzip', 'tar', 'ufw', 'certbot', 'python3-certbot-nginx'], reload: ['/usr/bin/systemctl reload nginx'] },
  php: { label: 'PHP 8.3 + nginx + composer', packages: ['nginx', 'git', 'curl', 'unzip', 'tar', 'ufw', 'certbot', 'python3-certbot-nginx', 'php8.3-fpm', 'php8.3-cli', 'php8.3-mbstring', 'php8.3-xml', 'php8.3-curl', 'php8.3-zip', 'php8.3-mysql', 'php8.3-pgsql', 'php8.3-intl', 'php8.3-bcmath', 'php8.3-gd', 'composer'], reload: ['/usr/bin/systemctl reload nginx', '/usr/bin/systemctl reload php8.3-fpm'] },
  node: { label: 'Node.js 22 + pm2 + nginx', packages: ['nginx', 'git', 'curl', 'unzip', 'tar', 'ufw', 'ca-certificates', 'certbot', 'python3-certbot-nginx'], reload: ['/usr/bin/systemctl reload nginx', '/usr/bin/systemctl restart *.service'], extra: ['curl -fsSL https://deb.nodesource.com/setup_22.x | bash -', 'apt-get install -y nodejs', 'npm install -g pm2', 'su - deploy -c "pm2 startup systemd -u deploy --hp /home/deploy" >/dev/null 2>&1 || true', 'env PATH=$PATH:/usr/bin pm2 startup systemd -u deploy --hp /home/deploy >/dev/null 2>&1 || true'] },
  python: { label: 'Python 3 + nginx', packages: ['nginx', 'git', 'curl', 'unzip', 'tar', 'ufw', 'certbot', 'python3-certbot-nginx', 'python3', 'python3-venv', 'python3-pip', 'build-essential', 'libpq-dev'], reload: ['/usr/bin/systemctl reload nginx', '/usr/bin/systemctl restart *.service'] },
  docker: { label: 'Docker + compose + nginx', packages: ['nginx', 'git', 'curl', 'unzip', 'tar', 'ufw', 'ca-certificates', 'certbot', 'python3-certbot-nginx'], reload: ['/usr/bin/systemctl reload nginx'], extra: ['curl -fsSL https://get.docker.com | sh', 'usermod -aG docker deploy', 'systemctl enable --now docker'] },
};

function yamlList(items, indent = '  ') { return items.map((i) => `${indent}- ${JSON.stringify(i)}`).join('\n'); }

/**
 * @param {{recipe:string, publicKey:string, appName?:string, user?:string, timezone?:string}} o
 * @returns {string} cloud-config YAML
 */
function cloudInit(o) {
  const r = RECIPES[o.recipe] || RECIPES.base;
  const user = /^[a-z_][a-z0-9_-]{0,31}$/.test(o.user || '') ? o.user : 'deploy';
  const app = String(o.appName || 'app').toLowerCase().replace(/[^a-z0-9_.-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'app';
  const pub = String(o.publicKey || '').trim();
  if (!/^(ssh-(ed25519|rsa|ecdsa)|ecdsa-sha2-nistp\d+) [A-Za-z0-9+/=]+/.test(pub)) throw Object.assign(new Error('publicKey must be an OpenSSH public key line'), { status: 400 });
  const routing = ['/usr/bin/tee /etc/nginx/sites-available/*', '/usr/bin/ln -sfn /etc/nginx/sites-available/* /etc/nginx/sites-enabled/*', '/usr/sbin/nginx -t', '/usr/bin/certbot *'];
  const sudoers = [`${user} ALL=(root) NOPASSWD: ${[...r.reload, ...routing].join(', ')}`];
  const runcmd = [
    'ufw allow OpenSSH', 'ufw allow 80/tcp', 'ufw allow 443/tcp', 'ufw --force enable',
    ...(r.extra || []),
    `mkdir -p /var/www/${app} && chown -R ${user}:${user} /var/www/${app}`,
    `rm -f /etc/nginx/sites-enabled/default`,
    'systemctl enable --now nginx',
    `touch /var/lib/cloud/instance/ascension-ready`,
  ];
  return `#cloud-config
# generated by The Ascension (Server Tools): recipe: ${r.label}
package_update: true
package_upgrade: false
timezone: ${o.timezone || 'UTC'}
users:
  - name: ${user}
    groups: [sudo, www-data]
    shell: /bin/bash
    sudo: ${JSON.stringify(sudoers[0])}
    lock_passwd: true
    ssh_authorized_keys:
${yamlList([pub], '      ')}
packages:
${yamlList(r.packages)}
write_files:
  - path: /etc/sudoers.d/90-${user}-ascension
    permissions: '0440'
    content: |
      ${sudoers[0]}
  - path: /etc/nginx/sites-available/${app}
    content: |
      server {
          listen 80 default_server;
          server_name _;
          root /var/www/${app}/current${r === RECIPES.php ? '/public' : ''};
          index index.php index.html;
          location / { try_files $uri $uri/ ${r === RECIPES.php ? '/index.php?$query_string' : '=404'}; }
${r === RECIPES.php ? `          location ~ \\.php$ {
              include snippets/fastcgi-php.conf;
              fastcgi_pass unix:/run/php/php8.3-fpm.sock;
              fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
              fastcgi_param DOCUMENT_ROOT $realpath_root;
          }` : ''}
      }
runcmd:
${yamlList(runcmd)}
  - ln -sf /etc/nginx/sites-available/${app} /etc/nginx/sites-enabled/${app}
  - nginx -t && systemctl reload nginx
final_message: "The Ascension: server ready after $UPTIME seconds"
`;
}

module.exports = { RECIPES, cloudInit };
