'use strict';
/* Starting a WordPress project with nothing to start from.
 *
 * "Connect a repository" assumes a repository. Plenty of WordPress work does not begin with one: you
 * have a server, a domain and an idea. This writes the smallest thing that is nonetheless a real
 * project - a theme that renders, a place for plugins, a ship.json that says how to deploy it, and a
 * .gitignore that already knows what never belongs in the repository - into a folder you choose.
 *
 * What it deliberately does NOT contain is WordPress itself. Core is downloaded and verified at
 * build time (wp.js) and laid under your files on every deploy, so it is never committed, never
 * stale, and updating it is a version bump rather than a merge.
 *
 * The result is an ordinary local-folder repository. Everything after this point - detect, plan,
 * ship, rollback - is the normal path, with no special case for having been generated.
 */

const fs = require('fs');
const fsp = require('fs/promises');
const path = require('path');
const { execFile } = require('child_process');
const { assertLocalRoot } = require('./targets/local');

const err = (m, status = 400) => Object.assign(new Error(m), { status });

const SLUG_RE = /^[a-z][a-z0-9-]{1,39}$/;
/** WordPress reads the theme folder name as its slug, so it has to be one. */
function slugify(input, fallback = 'my-theme') {
  const s = String(input || '').toLowerCase().normalize('NFKD').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40);
  return SLUG_RE.test(s) ? s : fallback;
}
const titleCase = (slug) => slug.split('-').filter(Boolean).map((w) => w[0].toUpperCase() + w.slice(1)).join(' ');
const esc = (s) => String(s).replace(/\*\//g, '* /'); // nothing written here may close a PHP comment

/* ------------------------------------------------------------- the theme */

/* Small, but a real theme: it renders posts and pages, supports the things WordPress expects a
   modern theme to declare, and loads its own stylesheet. Enough that the site works the moment it
   is activated, and little enough to read in one sitting before replacing it. */

const themeStyle = ({ themeName, slug, siteName }) => `/*
Theme Name: ${esc(themeName)}
Theme URI:
Author: ${esc(siteName)}
Description: The starting theme for ${esc(siteName)}, generated by Server Tools. Edit it, rename it, or delete it and use your own.
Version: 1.0.0
Requires at least: 6.0
Tested up to: 7.1
Requires PHP: 8.0
License: GPL-2.0-or-later
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Text Domain: ${slug}
*/

:root { --measure: 68ch; --ink: #17202a; --muted: #5b6875; --bg: #fff; --accent: #2f6feb; }
@media (prefers-color-scheme: dark) { :root { --ink: #e8edf3; --muted: #9aa7b4; --bg: #12171d; --accent: #7aa7ff; } }

* { box-sizing: border-box; }
body { margin: 0; background: var(--bg); color: var(--ink); font: 16px/1.65 system-ui, -apple-system, "Segoe UI", Roboto, sans-serif; }
a { color: var(--accent); }
.wrap { max-width: var(--measure); margin: 0 auto; padding: 0 1.25rem; }
.site-header { border-bottom: 1px solid color-mix(in srgb, var(--ink) 12%, transparent); padding: 1.5rem 0; }
.site-title { margin: 0; font-size: 1.35rem; letter-spacing: -.01em; }
.site-title a { color: inherit; text-decoration: none; }
.site-description { margin: .25rem 0 0; color: var(--muted); font-size: .95rem; }
.site-nav ul { list-style: none; display: flex; flex-wrap: wrap; gap: 1rem; margin: .85rem 0 0; padding: 0; }
.site-main { padding: 2rem 0 3rem; }
.entry { padding-bottom: 2rem; margin-bottom: 2rem; border-bottom: 1px solid color-mix(in srgb, var(--ink) 10%, transparent); }
.entry:last-child { border-bottom: 0; }
.entry-title { margin: 0 0 .35rem; font-size: 1.6rem; line-height: 1.2; }
.entry-title a { color: inherit; text-decoration: none; }
.entry-title a:hover { text-decoration: underline; }
.entry-meta { margin: 0 0 1rem; color: var(--muted); font-size: .85rem; }
.entry-thumb img { max-width: 100%; height: auto; border-radius: 10px; }
.site-footer { border-top: 1px solid color-mix(in srgb, var(--ink) 12%, transparent); padding: 1.5rem 0; color: var(--muted); font-size: .9rem; }
.pagination { display: flex; gap: 1rem; }
`;

const themeFunctions = ({ slug, themeName }) => `<?php
/**
 * ${esc(themeName)} - theme setup.
 *
 * Generated by Server Tools as a starting point. It is yours: edit it freely.
 *
 * @package ${slug}
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit; // not loaded through WordPress
}

define( '${slug.toUpperCase().replace(/-/g, '_')}_VERSION', '1.0.0' );

/**
 * Tell WordPress what this theme supports.
 */
function ${slug.replace(/-/g, '_')}_setup() {
	load_theme_textdomain( '${slug}', get_template_directory() . '/languages' );
	add_theme_support( 'title-tag' );
	add_theme_support( 'post-thumbnails' );
	add_theme_support( 'automatic-feed-links' );
	add_theme_support( 'responsive-embeds' );
	add_theme_support( 'html5', array( 'search-form', 'comment-form', 'comment-list', 'gallery', 'caption', 'style', 'script' ) );
	register_nav_menus( array( 'primary' => __( 'Primary menu', '${slug}' ) ) );
}
add_action( 'after_setup_theme', '${slug.replace(/-/g, '_')}_setup' );

/**
 * Load the stylesheet, versioned so a deploy busts the cache.
 */
function ${slug.replace(/-/g, '_')}_assets() {
	wp_enqueue_style( '${slug}', get_stylesheet_uri(), array(), ${slug.toUpperCase().replace(/-/g, '_')}_VERSION );
}
add_action( 'wp_enqueue_scripts', '${slug.replace(/-/g, '_')}_assets' );
`;

const themeHeader = ({ slug }) => `<?php
/**
 * The opening markup for every page.
 *
 * @package ${slug}
 */
?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
	<meta charset="<?php bloginfo( 'charset' ); ?>">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<?php wp_head(); ?>
</head>
<body <?php body_class(); ?>>
<?php wp_body_open(); ?>
<header class="site-header">
	<div class="wrap">
		<p class="site-title"><a href="<?php echo esc_url( home_url( '/' ) ); ?>" rel="home"><?php bloginfo( 'name' ); ?></a></p>
		<?php if ( get_bloginfo( 'description' ) ) : ?>
			<p class="site-description"><?php bloginfo( 'description' ); ?></p>
		<?php endif; ?>
		<nav class="site-nav" aria-label="<?php esc_attr_e( 'Primary menu', '${slug}' ); ?>">
			<?php wp_nav_menu( array( 'theme_location' => 'primary', 'container' => false, 'fallback_cb' => false, 'depth' => 1 ) ); ?>
		</nav>
	</div>
</header>
<main class="site-main">
	<div class="wrap">
`;

const themeFooter = ({ slug }) => `<?php
/**
 * The closing markup for every page.
 *
 * @package ${slug}
 */
?>
	</div>
</main>
<footer class="site-footer">
	<div class="wrap">
		<p>&copy; <?php echo esc_html( gmdate( 'Y' ) ); ?> <?php bloginfo( 'name' ); ?></p>
	</div>
</footer>
<?php wp_footer(); ?>
</body>
</html>
`;

const themeIndex = ({ slug }) => `<?php
/**
 * The fallback template: WordPress uses it whenever nothing more specific exists.
 *
 * @package ${slug}
 */

get_header();

if ( have_posts() ) :
	while ( have_posts() ) :
		the_post();
		?>
		<article id="post-<?php the_ID(); ?>" <?php post_class( 'entry' ); ?>>
			<h1 class="entry-title">
				<?php if ( is_singular() ) : ?>
					<?php the_title(); ?>
				<?php else : ?>
					<a href="<?php the_permalink(); ?>"><?php the_title(); ?></a>
				<?php endif; ?>
			</h1>
			<?php if ( 'post' === get_post_type() ) : ?>
				<p class="entry-meta"><?php echo esc_html( get_the_date() ); ?></p>
			<?php endif; ?>
			<?php if ( has_post_thumbnail() ) : ?>
				<div class="entry-thumb"><?php the_post_thumbnail( 'large' ); ?></div>
			<?php endif; ?>
			<div class="entry-content">
				<?php
				the_content();
				wp_link_pages();
				?>
			</div>
		</article>
		<?php
	endwhile;

	the_posts_pagination( array( 'class' => 'pagination' ) );
else :
	?>
	<p><?php esc_html_e( 'Nothing here yet.', '${slug}' ); ?></p>
	<?php
endif;

get_footer();
`;

/* --------------------------------------------------- the project around it */

const GITIGNORE = `# WordPress core is downloaded and verified at build time, never committed.
/wp-admin/
/wp-includes/
/wp-*.php
!/wp-content/

# Generated on every deploy from the vault entry this project's ship.json names.
wp-config.php

# User uploads are shared storage on the server: they outlive releases and are not code.
wp-content/uploads/

# Written by plugins at runtime.
wp-content/cache/
wp-content/upgrade/
wp-content/backup*/
wp-content/debug.log
wp-content/advanced-cache.php
wp-content/object-cache.php

# Local noise
node_modules/
vendor/
.DS_Store
Thumbs.db
*.log
`;

const readme = ({ siteName, slug, themeName, version, configFromVault }) => `# ${siteName}

A WordPress project. WordPress itself is **not** in this repository: core ${version === 'latest' ? '(latest)' : version} is
downloaded from wordpress.org at build time, checked against the SHA-1 they publish, and laid
underneath these files on every deploy. What lives here is only what is yours.

\`\`\`
wp-content/themes/${slug}/   your theme, ready to edit
wp-content/plugins/          plugins you maintain yourself
wp-content/mu-plugins/       must-use plugins: loaded always, cannot be deactivated
ship.json                    how this project is built and deployed
\`\`\`

## Deploying it

The target was set up alongside this folder, so **Plan** then **Ship** from the Deployments page.
Each deploy assembles a fresh release - verified core, plus these files over the top - and swaps it
in atomically. Rolling back swaps the previous one back.

## Before the first visit

1. Create the database and a user for it. A deploy never creates, migrates or touches one.
2. Put the credentials in the vault entry **${configFromVault || '(name one in ship.json as stack.wordpress.configFromVault)'}**:
   \`\`\`
   WORDPRESS_DB_NAME=…
   WORDPRESS_DB_USER=…
   WORDPRESS_DB_PASSWORD=…
   WORDPRESS_DB_HOST=localhost
   \`\`\`
3. Ship, then open \`/wp-admin/install.php\` once and finish the five-minute install.
4. In **Appearance → Themes**, activate **${themeName}**. WordPress starts on its own bundled theme;
   yours is there waiting.

## Things that work differently here

- **Installing plugins and themes from wp-admin is switched off.** They would be written into a
  release directory that the next deploy replaces, so they would quietly disappear. Add them to
  \`wp-content/plugins/\` and commit them instead. If you would rather have the admin screens back on
  those terms, set \`WORDPRESS_ALLOW_FILE_MODS=true\` in the vault entry.
- **Media uploads are safe.** They live outside the releases and survive every deploy.
- **Updating WordPress is a version bump.** Change \`stack.wordpress.version\` in \`ship.json\` and ship.
`;

const shipJson = ({ siteName, version, configFromVault }) => JSON.stringify({
  version: 1,
  name: slugify(siteName, 'site'),
  stack: {
    type: 'php',
    framework: 'wordpress',
    wordpress: { version: version || 'latest', contentDir: 'wp-content', core: 'download', intoDir: '', configFromVault: configFromVault || null },
  },
  runtime: { kind: 'php-fpm', docroot: '.' },
  shared: { files: [], dirs: ['wp-content/uploads'] },
  health: { path: '/', expectStatus: [200, 399] },
}, null, 2) + '\n';

/* ------------------------------------------------------------------ write */

/** A folder we may write a new project into: nothing there, or nothing that matters. */
async function assertEmptyEnough(dir) {
  let entries;
  try { entries = await fsp.readdir(dir); } catch { return; } // does not exist yet: fine
  const real = entries.filter((e) => !['.git', '.DS_Store', 'Thumbs.db', 'desktop.ini'].includes(e));
  if (real.length) throw err(`${dir} already has files in it (${real.slice(0, 4).join(', ')}${real.length > 4 ? ', …' : ''}); choose an empty folder so nothing of yours is overwritten`);
}

/** Best effort: a generated project is more useful as a git repository than as a folder. */
function gitInit(dir) {
  return new Promise((resolve) => {
    execFile('git', ['init', '--initial-branch=main'], { cwd: dir, timeout: 15000 }, (e) => resolve(!e));
  });
}

/**
 * Write a new WordPress project into `dir`.
 *
 * @param {object} o
 * @param {string} o.dir              absolute folder to create the project in (must be empty)
 * @param {string} [o.name]           what to call the site; defaults to the folder name
 * @param {string} [o.themeSlug]      theme folder name; defaults to <name>-theme
 * @param {string} [o.version]        WordPress version to pin, or "latest"
 * @param {string} [o.configFromVault] vault entry holding the WORDPRESS_DB_* settings
 * @param {boolean} [o.git]           run `git init` afterwards (default true)
 * @returns {Promise<{path, name, themeSlug, themeName, files: string[], git: boolean}>}
 */
async function createProject({ dir, name, themeSlug, version = 'latest', configFromVault = null, git = true } = {}) {
  const root = assertLocalRoot(dir, 'folder');
  await assertEmptyEnough(root);

  const siteName = String(name || path.basename(root)).trim().slice(0, 60) || path.basename(root);
  // a name that slugifies to nothing ("???") must not leave "-theme" behind as the folder name
  const fromName = slugify(siteName, '');
  const slug = slugify(themeSlug || (fromName ? `${fromName}-theme` : 'my-theme'), 'my-theme');
  const themeName = titleCase(slug);
  const themeDir = `wp-content/themes/${slug}`;
  const ctx = { siteName, slug, themeName, version, configFromVault };

  const files = {
    'ship.json': shipJson(ctx),
    '.gitignore': GITIGNORE,
    'README.md': readme(ctx),
    [`${themeDir}/style.css`]: themeStyle(ctx),
    [`${themeDir}/functions.php`]: themeFunctions(ctx),
    [`${themeDir}/header.php`]: themeHeader(ctx),
    [`${themeDir}/footer.php`]: themeFooter(ctx),
    [`${themeDir}/index.php`]: themeIndex(ctx),
    // git does not track empty directories, and these two are the point of the project
    'wp-content/plugins/.gitkeep': '',
    'wp-content/mu-plugins/.gitkeep': '',
  };

  await fsp.mkdir(root, { recursive: true });
  for (const [rel, body] of Object.entries(files)) {
    const p = path.join(root, rel);
    await fsp.mkdir(path.dirname(p), { recursive: true });
    await fsp.writeFile(p, body);
  }

  return { path: root, name: siteName, themeSlug: slug, themeName, files: Object.keys(files).sort(), git: git ? await gitInit(root) : false };
}

module.exports = { createProject, slugify, titleCase, assertEmptyEnough, GITIGNORE, shipJson, readme };
